chore: 添加版本校验以阻止发布 SNAPSHOT 版本
在手动发布和文件发布的工作流中添加了版本校验步骤，确保不会发布包含 SNAPSHOT 的版本。

diff --git a/.github/workflows/release-by-file.yml b/.github/workflows/release-by-file.yml
--- a/.github/workflows/release-by-file.yml
+++ b/.github/workflows/release-by-file.yml
@@ -29,6 +29,12 @@ jobs:
           echo "RELEASE_VERSION=${{steps.metadata.outputs.current-version}}" >> $GITHUB_ENV
           echo "NEXT_VERSION=${{steps.metadata.outputs.next-version}}" >> $GITHUB_ENV
 
+      - name: Validate version
+        if: contains(env.RELEASE_VERSION, 'SNAPSHOT')
+        run: |
+          echo '::error::Cannot release a SNAPSHOT version.'
+          exit 1
+          
       - name: Checkout Source
         uses: actions/checkout@v4
         with:
diff --git a/.github/workflows/release-by-manual.yml b/.github/workflows/release-by-manual.yml
--- a/.github/workflows/release-by-manual.yml
+++ b/.github/workflows/release-by-manual.yml
@@ -32,6 +32,12 @@ jobs:
           echo "RELEASE_VERSION=${{github.event.inputs.version}}" >> $GITHUB_ENV
           echo "NEXT_VERSION=${{github.event.inputs.nextVersion}}" >> $GITHUB_ENV
 
+      - name: Validate version
+        if: contains(env.RELEASE_VERSION, 'SNAPSHOT')
+        run: |
+          echo '::error::Cannot release a SNAPSHOT version.'
+          exit 1
+
       - name: Checkout Source
         uses: actions/checkout@v4
         with:
