chore: add version validation and milestone review to release workflow
Add a step to validate that the released version is not a SNAPSHOT version, and add a milestone review step using the radcortez/milestone-review-action in the release workflow.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -45,6 +45,12 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate version
+        if: contains(github.event.inputs.version, 'SNAPSHOT')
+        run: |
+          echo '::error::Cannot release a SNAPSHOT version.'
+          exit 1
+
       - name: Checkout Source
         uses: actions/checkout@v4
         with:
@@ -67,6 +73,12 @@ jobs:
           server-password: MAVEN_PASSWORD
           gpg-private-key: ${{ secrets.GPG_SECRET_KEY }} # macOS: gpg --armor --export-secret-key
           gpg-passphrase: MAVEN_GPG_PASSPHRASE
+
+      - name: Review Milestone
+        uses: radcortez/milestone-review-action@main
+        with:
+          github-token: ${{secrets.GITHUB_TOKEN}}
+          milestone-title: ${{github.event.inputs.version}}
 
       - name: Set release version
         run: |
